name: Deploy to GCP App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        export_default_credentials: true

    - name: Configure gcloud project
      run: gcloud config set project githubdeploy

    - name: Build and deploy to App Engine
      run: gcloud app deploy cloudbuild.yaml
      
