
name: Copy Code to Azure Storage
on: push
jobs:
  my-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Upload files to Azure Storage Account
      run: |
        az storage blob upload-batch --account-name storageaccgithub --destination repo --source .
